# SPDX-PackageName: "ACTS"
# SPDX-FileCopyrightText: 2016 CERN
# SPDX-License-Identifier: MPL-2.0

version = 1

merge.message.title = "pull_request_title"
merge.message.body = "pull_request_body"
merge.message.cut_body_after = "--- END COMMIT MESSAGE ---"
merge.message.cut_body_and_text = true
merge.method = "squash"
merge.message.include_coauthors = true
merge.priority_merge_label = "automerge priority"
