# SPDX-PackageName: "ACTS"
# SPDX-FileCopyrightText: 2016 CERN
# SPDX-License-Identifier: MPL-2.0

rules:
  - required_checks:
      - Lint PR / Validate PR title
      - milestone-set
    required_pattern:
      - "policy-bot: *"

  - branch_filter:
     - "main"
     - "develop/*"
    paths_ignore:
     - "docs/*"

    required_checks:
     - Docs / docs
     - Analysis / build_debug
     - SonarCloud Code Analysis

    required_pattern:
     - "Builds / *"
     - "Checks / *"
     - "CI Bridge / *"

  - branch_filter:
     - "main"
     - "develop/*"
    paths:
     - "docs/*"
    required_checks:
     - Docs / docs
