# SPDX-PackageName: "ACTS"
# SPDX-FileCopyrightText: 2016 CERN
# SPDX-License-Identifier: MPL-2.0

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
    patch: off
