version = 1

[[annotations]]
path = ["**/*.json", "**/*.onnx", "Scripts/requirements.in", "Python/tests/root_file_hashes.txt", "Python/tests/requirements.in", "Detectors/MuonSpectrometerMockupDetector/MuonChamber.gdml"]
precedence = "aggregate"
SPDX-PackageName = "ACTS"
SPDX-FileCopyrightText = "2016 CERN"
SPDX-License-Identifier = "MPL-2.0"
