# SPDX-PackageName: "ACTS"
# SPDX-FileCopyrightText: 2016 CERN
# SPDX-License-Identifier: MPL-2.0

checks:
  "*":
    Chi2Test:
      threshold: 0.01
    KolmogorovTest:
      threshold: 0.68
    RatioCheck:
      threshold: 3
    ResidualCheck:
      threshold: 3
    IntegralCheck:
      threshold: 3
