name: "Dependencies action"
description: "Reusable action that sets up dependencies for the ACTS CI build"
inputs:
  xcode-version:
    description: "Which Xcode version to use (only for macOS)"
    required: true
    default: ""
# outputs:
#   example_output:
#     description: "An example output"
runs:
  using: "composite"
  steps:
    - name: Set up Spack
      uses: spack/setup-spack@v2

    - name: Apply spack patch
      shell: bash
      working-directory: spack
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        curl https://patch-diff.githubusercontent.com/raw/spack/spack/pull/47370.patch | git am

    - name: Locate OpenGL
      shell: bash
      run: "${GITHUB_ACTION_PATH}/opengl.sh"

    - name: Get spack lock file name
      shell: bash
      run: |
        arch=$(spack arch --family)
        if [[ $arch == darwin* ]]; then
          lock_file="spack-${arch}-${{ inputs.xcode }}.lock"
        else
          lock_file="spack-${arch}.lock"
        fi
        echo "Lock file: ${lock_file}"
        echo "SPACK_LOCK_FILE=${lock_file}" >> $GITHUB_ENV

    # - name: Setup Xcode version
    #   if: startsWith(inputs.os, 'macos')
    #   uses: maxim-lobanov/setup-xcode@v1
    #   with:
    #     xcode-version: "${{ inputs.xcode }}"
