name: "Dependencies action"
description: "Reusable action that sets up dependencies for the ACTS CI build"
inputs:
  xcode-version:
    description: "Which Xcode version to use (only for macOS)"
    required: true
    default: "16.0.0"
  dependency-tag:
    description: "Which dependency tag to use"
    required: true
    default: "v6-test"
runs:
  using: "composite"
  steps:
    - name: Set up Spack
      uses: spack/setup-spack@v2

    - name: Apply spack patch
      shell: bash
      working-directory: spack
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        curl https://patch-diff.githubusercontent.com/raw/spack/spack/pull/47370.patch | git am


    - name: Add spack buildcache mirror
      shell: bash
      run: |
        spack mirror add acts-spack-buildcache oci://ghcr.io/acts-project/spack-buildcache --unsigned

    - name: Locate OpenGL
      shell: bash
      run: "${GITHUB_ACTION_PATH}/opengl.sh"

    - name: Get spack lock file name
      shell: bash
      run: |
        arch=$(spack arch --family)
        if [[ $arch == darwin* ]]; then
          lock_file="spack-${arch}-xcode${{ inputs.xcode-version }}.lock"
        else
          lock_file="spack-${arch}.lock"
        fi
        echo "Lock file: ${lock_file}"
        echo "SPACK_LOCK_FILE=${lock_file}" >> "$GITHUB_ENV"

    - name: Setup Xcode version
      if: startsWith(runner.os, 'macos')
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "${{ inputs.xcode-version }}"

    - name: Get spack lock file from tag
      shell: bash
      run: |
        url="https://github.com/acts-project/ci-dependencies/releases/download/${{ inputs.dependency-tag }}/${SPACK_LOCK_FILE}"
        echo "URL: ${url}"
        curl -L -o spack.lock $url

    - name: Create spack environment
      shell: bash
      run: |
        spack env create ci spack.lock --with-view $PWD/dependencies
        spack -e ci spec
        spack -e ci find
        spack -e ci install --use-buildcache only
        ls -al
        echo "PATH=$PWD/dependencies/bin:$PATH" >> "$GITHUB_ENV"

    - name: Install Geant4 data
      shell: bash
      run: |
        spack -e ci install --add geant4-data
        "${GITHUB_ACTION_PATH}/with_spack_env.sh" ci env | grep G4 >> "$GITHUB_ENV"
