name: Builds

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'
      - 'develop/**'
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_MAXSIZE: 500M
  CCACHE_KEY_SUFFIX: r1

jobs:
  macos:
    runs-on: macos-13
    env:
      INSTALL_DIR: ${{ github.workspace }}/install
      ACTS_LOG_FAILURE_THRESHOLD: WARNING
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Print architecture
        run: uname -p

      - name: Install dependencies
        run: >
          brew install cmake eigen ninja ccache
          && sudo mkdir /usr/local/acts
          && sudo chown $USER /usr/local/acts
          && wget --verbose --progress=dot:giga --continue --retry-connrefused --tries=5 --timeout=2 -O deps.tar.gz https://acts.web.cern.ch/ACTS/ci/macOS/deps.80e4e05.tar.gz
          && tar -xf deps.tar.gz -C /usr/local/acts
          && /usr/local/acts/bin/python3.10 -m pip install pyyaml jinja2

      - name: Restore ccache
        uses: actions/cache/restore@v4
        id: ccache-restore
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os  }}-ccache_${{ env.CCACHE_KEY_SUFFIX }}_${{ github.sha }}
          restore-keys: |
            ${{ runner.os  }}-ccache_${{ env.CCACHE_KEY_SUFFIX }}_

      - name: Configure
        # setting CMAKE_CXX_STANDARD=17 is a workaround for a bug in the
        # dd4hep CMake configuration that gets triggered on recent CMake
        # versions such as the one installed via homebrew
        run: >
          ccache -z &&
          cmake -B build -S .
          -GNinja
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DPython_EXECUTABLE=/usr/local/acts/bin/python3.10
          -DDD4HEP_DEBUG_CMAKE=ON
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_FLAGS=-Werror
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
          -DCMAKE_PREFIX_PATH=/usr/local/acts
          -DACTS_BUILD_EVERYTHING=ON
          -DACTS_BUILD_ODD=ON
          -DACTS_ENABLE_LOG_FAILURE_THRESHOLD=ON
          -DACTS_FORCE_ASSERTIONS=ON
          -DACTS_BUILD_EXAMPLES_EDM4HEP=ON
          -DACTS_BUILD_PLUGIN_ACTSVG=ON
      - name: Build
        run: cmake --build build
      - name: ccache stats
        run: ccache -s
      - name: Save ccache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}
      - name: Unit tests
        run: cmake --build build --target test
      - name: Integration tests
        run: cmake --build build --target integrationtests
      - name: Install
        run: cmake --build build --target install
      - uses: actions/upload-artifact@v4
        with:
          name: acts-macos
          path: ${{ env.INSTALL_DIR }}
      - name: Downstream configure
        run: >
          cmake -B build-downstream -S Tests/DownstreamProject
          -GNinja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_FLAGS=-Werror
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_PREFIX_PATH="${INSTALL_DIR};/usr/local/acts"
      - name: Downstream build
        run: cmake --build build-downstream
      - name: Downstream run
        run: ./build-downstream/bin/ShowActsVersion
