# SPDX-PackageName: "ACTS"
# SPDX-FileCopyrightText: 2016 CERN
# SPDX-License-Identifier: MPL-2.0

name: Check PR labels

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  check_pr_labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
          dot: true
