name: Check PR milestone

on:
  pull_request_target:
    types: [milestoned, demilestoned]
    branches:
      - main

jobs:
  check_milestone:
    if: ${{ github.event.issue.pull_request || github.event.pull_request }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - run: |
      #     echo "${{ toJSON(github.event) }}"

      - name: "Check for milestone on PR"
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context);


            let milestone = null;
            let pr_number = null;
            if(context.eventName === "pull_request_target") {
                pr_number = context.payload.pull_request.number;
                milestone = context.payload.pull_request.milestone;
                console.log(`PR TARGET Milestone ${milestone}`);
            } else if(context.eventName === "issues" && "pull_request" in context.payload.issue) {
                pr_number = context.payload.issue.number;
                milestone = context.payload.issue.milestone;
            }

            let conclusion = null;
            let output = {};
            if(milestone !== null) {
                console.log(`Milestone is ${milestone.title}`);
            } else {
                console.log("No milestone");
                core.setFailed("Please add a version milestone");
            }
