name: Check PR milestone

on:
  pull_request_target:
    types: [milestoned, demilestoned, opened, reopened]
    branches:
      - main

jobs:
  check_milestone:
    if: ${{ github.event.issue.pull_request || github.event.pull_request }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - run: |
      #     echo "${{ toJSON(github.event) }}"

      - name: "Check for milestone on PR"
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context);
            let milestone = context.payload.pull_request.milestone;

            if(context.action == 'opened' || context.action == 'reopened') {
              if(milestone !== null) {
                  core.notice(`Milestone is ${milestone.title}`);
              } else {
                const milestones = await github.rest.issues.listMilestones({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: "open"
                });
                for (const milestone of milestones.data) {
                  if (milestone.title === "next") {
                    core.notice(`No milestone set, setting default milestone: ${default_milestone.title}`);

                    await github.rest.issues.update({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: context.issue.number,
                      milestone: milestone.number
                    });
                    return;
                  }
                }

                core.warning("Could not find default milestone named 'next'");

              }

            }
            else {
              if(milestone !== null) {
                  core.notice(`Milestone is ${milestone.title}`);
              } else {
                  core.setFailed("No milestone: Please add a version milestone");
              }
            }
